name: ModReq
main: modreq.ModReq
config-version: 3.0
author: Sgt_Tailor
dev-url: http://dev.bukkit.org/server-mods/modreq/
description: A Moderator Request plugin
version: "${version}"
commands:
    modreload:
        description: reload modreq
        usage: /modreqreload
        permission: modreq.reload
    ticket:
        description: All the modreq command are under this
        usage: /ticket <id>
    mods:
        description: returns a list of online mods
        usage: /mods
        permission: modreq.mods
permissions:
    modreq.moderator:
        default: op
        description: allows person to claim open tickets, close them and set them to pending. It does not allow them to reopen tickets, or claim pending ones.
        children:
            modreq.show: true
            modreq.tp: true
            modreq.claim.normal: true
            modreq.close: true
            modreq.setpending: true
            modreq.comment-all: true
    modreq.admin:
        default: op
        description: gets everything moderator gets, plus the ability to overwrite claim a ticket, reopen tickets, claim pending ticket, overwrite comment limit.
        children:
            modreq.moderator: true
            modreq.reopen: true
            modreq.overwrite.claim: true
            modreq.overwrite.close: true
            modreq.overwrite.commentlimit: true
            modreq.claim.pending: true
    modreq.overwrite.claim:
        default: op
        description: allows a person to overwrite claiming a ticket
    modreq.overwrite.close:
        default: op
        description: allows a person to overwrite closing a ticket
    modreq.overwrite.commentlimit:
        default: op
        description: allows a person to overwrite the comment limit
    mod.reload:
        default: op
        description: allows a person to do /modreqreload
    modreq.mods:
        default: true
        description: allows a person to do /mods
    modreq.show:
        description: allows a person to view tickets
        default: op
    modreq.status:
        description: allows a person to view their own ticket
        default: true
    modreq.escalate:
        description: allows a person to escalate a ticket
        default: op
    modreq.tp:
        description: allows a person to teleport to a ticket location
        default: op
    modreq.claim.normal:
        default: op
        description: allows a person to claim an open ticket
    modreq.claim.pending:
        default: op
        description: allows a person to claim pending tickets.
    modreq.create:
        description: allows a person to submit a ticket
        default: true
    modreq.close:
        description: allows a person to close a ticket
        default: op
    modreq.reopen:
        description: allows a person to re-open a ticket
        default: op
    modreq.comment-all:
        description: Allows a person to comment on all tickets
        default: op